"""
pages/3_Reports.py
Browse and download previously generated research reports.
"""

from pathlib import Path

import streamlit as st

from database.models import list_reports
from ui.styles import inject_custom_css, render_empty_state, render_footer, render_header

st.set_page_config(page_title="Reports · Agentic RAG", page_icon="📄", layout="wide")
inject_custom_css(st)
render_header(st)

st.markdown("## 📄 Research Reports")
st.caption("All Markdown research reports generated by the Report Generator Agent.")

st.markdown("---")

reports = list_reports()

if not reports:
    render_empty_state(
        st,
        icon="🗒️",
        title="No reports yet",
        subtitle="Ask a research question in the chat to generate your first report.",
    )
else:
    # Filters
    col1, col2 = st.columns([3, 1])
    with col1:
        search_term = st.text_input("🔍 Search by query text", placeholder="e.g. climate change")
    with col2:
        min_confidence = st.slider("Min. Confidence", 0.0, 1.0, 0.0, 0.05)

    filtered = reports
    if search_term:
        filtered = [r for r in filtered if search_term.lower() in r.query.lower()]
    if min_confidence > 0:
        filtered = [
            r for r in filtered if (r.confidence_score or 0) >= min_confidence
        ]

    st.caption(f"Showing {len(filtered)} of {len(reports)} reports")
    st.markdown("")

    for r in filtered:
        with st.container(border=True):
            col1, col2, col3 = st.columns([4, 1, 1])
            with col1:
                st.markdown(f"**{r.query}**")
                st.caption(f"Generated: {r.created_at[:19]} · Session: `{r.session_id[:8]}...`")
            with col2:
                if r.confidence_score is not None:
                    st.metric("Confidence", f"{r.confidence_score:.2f}", label_visibility="collapsed")
                    st.caption("Confidence")
            with col3:
                if r.hallucination_score is not None:
                    st.metric("Hallucination", f"{r.hallucination_score:.2f}", label_visibility="collapsed")
                    st.caption("Hallucination")

            report_path = Path(r.file_path)
            if report_path.exists():
                with open(report_path, "rb") as f:
                    file_bytes = f.read()

                col_a, col_b = st.columns([1, 5])
                with col_a:
                    st.download_button(
                        "📥 Download",
                        data=file_bytes,
                        file_name=report_path.name,
                        mime="text/markdown",
                        key=f"dl_{r.id}",
                    )
                with col_b:
                    with st.expander("Preview"):
                        st.markdown(file_bytes.decode("utf-8"))
            else:
                st.caption("⚠️ Report file not found on disk.")

render_footer(st)
